name: build

on:
  push:
    tags-ignore: 
    - switch-portlibs
    - mingw-packages
    - macos-dylib
    paths-ignore:
    - scripts/mingw64/*/*
    - scripts/switch/*/*
    - images/*
    - CHANGELOG.md
    - README.md
    branches: [ "*" ]
  pull_request:
    paths-ignore:
    - scripts/mingw64/*/*
    - scripts/switch/*/*
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      nx:
        description: build nintendo switch
        type: boolean
      macos:
        description: build macos dmg
        type: boolean
      snap:
        description: build linux snap
        type: boolean
      flatpak:
        description: build linux flatpak
        type: boolean
      mingw64:
        description: build win64 mingw64
        type: boolean
      msvc:
        description: build win64 msvc
        type: boolean

permissions:
  contents: write

jobs:
  upload-release:
    needs: [ build-mingw, build-nx, build-macos ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v3
    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        name: Switchfin ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        draft: true
        files: |
          switchfin-windows-*/*.7z
          switchfin-macos-*/*.dmg
          switchfin-switch-opengl-*/*.nro
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/${{ github.ref_name }}/total?label=Downloads)

  build-nx:
    runs-on: ubuntu-latest
    if: ${{ inputs.nx || github.event_name != 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { driver: opengl }
        - { driver: deko3d, cmake: "-DUSE_DEKO3D=ON" }
        driver: [opengl, deko3d]
    container:
      image: devkitpro/devkita64
    env:
      BASE_URL: https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set workspace permissions
      run: |
        chown $(id -u):$(id -g) -R "$GITHUB_WORKSPACE"
        git config --system --add safe.directory '*'
    - name: Update dependencies
      run: |
        dkp-pacman --noconfirm -U $BASE_URL/hacBrewPack-3.05-1-any.pkg.tar.zst
        for pkg in curl-7.71.1-1 harfbuzz-8.3.0-1 libass-0.17.1-1 dav1d-1.3.0-1 ffmpeg-6.1-2 nspmini-main-1; do
          dkp-pacman --noconfirm -U $BASE_URL/switch-${pkg}-any.pkg.tar.zst
        done
    - name: Update mpv opengl
      if: ${{ matrix.driver == 'opengl' }}
      run: |
        for pkg in switch-libmpv-0.36.0-2; do
          dkp-pacman --noconfirm -U $BASE_URL/${pkg}-any.pkg.tar.zst
        done
    - name: Update mpv deko3d
      if: ${{ matrix.driver == 'deko3d' }}
      run: |
        dkp-pacman --noconfirm -R switch-libmpv
        for pkg in deko3d-0.5.0-1 libuam-master-1 switch-libmpv-deko3d-0.36.0-3; do
          dkp-pacman --noconfirm -U $BASE_URL/${pkg}-any.pkg.tar.zst
        done
    - name: Build nro
      run: |
        cmake -B build_switch -DCMAKE_BUILD_TYPE=Release -DPLATFORM_SWITCH=ON -DBUILTIN_NSP=ON -DVERSION_BUILD=${{ github.run_number }} ${{ matrix.cmake }}
        make -C build_switch Switchfin.nro -j$(nproc)
    - name: Set outputs
      id: vars
      run: echo "sha_short=${{ matrix.driver }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: switchfin-switch-${{ steps.vars.outputs.sha_short }}
        path: |
          build_switch/Switchfin.nro

  build-snap:
    runs-on: ubuntu-latest
    if: ${{ inputs.snap }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build snap
      run: |
        docker run --rm --tty --network host -v $PWD:/data -w /data/scripts --privileged diddledani/snapcraft:core20
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: switchfin-snap-${{ steps.vars.outputs.sha_short }}
        path: scripts/*.snap

  build-flatpak:
    runs-on: ubuntu-latest
    if: ${{ inputs.flatpak || github.event_name != 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64 ]
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set workspace permissions
      run: git config --system --add safe.directory '*'
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: switchfin-flatpak-${{ steps.vars.outputs.sha_short }}.flatpak
        manifest-path: scripts/flatpak.yaml
        cache-key: flatpak-builder-${{ hashFiles('scripts/flatpak.yaml') }}
        verbose: true
        arch: ${{ matrix.arch }}

  build-macos:
    runs-on: macos-latest
    if: ${{ inputs.macos || github.event_name != 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - tag: silicon
          arch: arm64
          target: "11.0"
        - tag: intel
          arch: x86_64
          target: "10.11"
          cmake: -DUSE_BOOST_FILESYSTEM=ON
        tag: [ silicon, intel ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install deps
      run: |
        brew install create-dmg dylibbundler
        curl -sSL https://github.com/dragonflylee/switchfin/releases/download/macos-dylib/dylib-0.36.0-${{ matrix.tag }}.tar.gz | tar zxf - -C ${{ github.workspace }}
    - name: Build App
      env:
        DYLD_LIBRARY_PATH: ${{ github.workspace }}/lib
      run: |
        cmake -B build ${{ matrix.cmake }} \
          -DCMAKE_PREFIX_PATH=${{ github.workspace }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DPLATFORM_DESKTOP=ON \
          -DUSE_SYSTEM_GLFW=ON \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DVERSION_BUILD=${{ github.run_number }}
        make -C build -j$(sysctl -n hw.ncpu)
    - name: Create DMG
      run: |
        mkdir -p dist
        mv build/Switchfin.app dist/
        cp README.md dist
        create-dmg --window-pos 200 120 --window-size 800 400 \
          --icon-size 100 --icon "Switchfin.app" 200 190 \
          --icon "README.md" 400 100 --hide-extension "Switchfin.app" \
          --app-drop-link 600 185 --volicon ./scripts/macos/dmg.icns \
          --volname "Switchfin" Switchfin-macOS-${{ matrix.tag }}.dmg "dist/"
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: switchfin-macos-${{ matrix.tag }}-${{ steps.vars.outputs.sha_short }}
        path: Switchfin-*.dmg

  build-mingw:
    if: ${{ inputs.mingw64 == true || github.event_name != 'workflow_dispatch'}}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { arch: x64, driver: opengl, msystem: MINGW64 }
        - { arch: x64, driver: d3d11, msystem: MINGW64, cmake: "-DUSE_D3D11=ON" }
        - { arch: x86, driver: opengl, msystem: MINGW32, cmake: "-DUSE_GL2=ON" }
        exclude:
        - { arch: x86, driver: d3d11 }
        arch: [ x64, x86 ]
        driver: [ opengl, d3d11 ]
    runs-on: windows-latest
    env:
      MSYSTEM: ${{ matrix.msystem }}
      MSYS2_PATH_TYPE: inherit
    defaults:
      run:
        shell: C:\shells\msys2bash.cmd {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependency
      run: |
        for pkg in glfw-3.4.0-1 curl-8.5.0-1 mpv-0.36.0-4 libwebp-1.3.2-1; do
          curl -sLO https://github.com/dragonflylee/switchfin/releases/download/mingw-packages/${MINGW_PACKAGE_PREFIX}-${pkg}-any.pkg.tar.zst
        done
        pacman -U --noconfirm *.pkg.tar.zst

        pacman -S --needed --noconfirm --noprogressbar \
          ${MINGW_PACKAGE_PREFIX}-cc \
          ${MINGW_PACKAGE_PREFIX}-ninja
    - name: Build
      run: |
        cmake -B build_mingw -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DPLATFORM_DESKTOP=ON \
          -DWIN32_TERMINAL=OFF \
          -DZLIB_USE_STATIC_LIBS=ON \
          -DUSE_SYSTEM_GLFW=ON \
          -DUSE_LIBROMFS=ON \
          -DVERSION_BUILD=${{ github.run_number }} ${{ matrix.cmake }}
        cmake --build build_mingw

        strip build_mingw/Switchfin.exe
        7z a -mx=9 Switchfin-windows-${{ matrix.arch }}-${{ matrix.driver }}.7z \
            ./build_mingw/Switchfin.exe ${MINGW_PREFIX}/bin/libmpv-2.dll README.md
    - name: Set outputs
      id: vars
      run: echo "sha_short=${{ matrix.arch }}-${{ matrix.driver }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: switchfin-windows-${{ steps.vars.outputs.sha_short }}
        path: Switchfin-*.7z

  build-msvc:
    runs-on: windows-latest
    if: ${{ inputs.msvc }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64 ]
    steps:
    - name: Install xmake
      shell: powershell
      run: |
        Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Cache xmake packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-{{ matrix.arch }}-xmake
        path: |
          ${{ runner.temp }}/.xmake/packages
    - name: Build
      shell: powershell
      run: |
        $env:path+=";$env:USERPROFILE\xmake"
        $env:XMAKE_GLOBALDIR="${{ runner.temp }}"
        xmake config -c -y -a ${{ matrix.arch }}
        xmake build -y
        cd build\windows\${{ matrix.arch }}\release
        7z a -mx=9 "$env:GITHUB_WORKSPACE\Switchfin-${{ matrix.arch }}-msvc.7z" *
    - name: Set outputs
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: switchfin-msvc-${{ matrix.arch }}-${{ steps.vars.outputs.sha_short }}
        path: Switchfin-*.7z
