name: switch-portlibs

on:
  push:
    tags: [ switch-portlibs ]
    paths: [ scripts/switch/*/* ]

permissions:
  contents: write

jobs:
  build-portlibs:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
    - name: Disable autocrlf
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
      with:
        sparse-checkout: scripts/switch
    - name: Install dependency
      run: |
        apt-get update
        apt-get install -y fakeroot zstd ninja-build libtool python3-distutils manpages-
        curl -sL https://bootstrap.pypa.io/get-pip.py | python3 -
        pip3 install meson mako

        dkp-pacman --noconfirm -U scripts/switch/dkp-*.zst
    - name: Build dekotools
      run: |
        apt-get install -y bison flex g++ manpages-
        git clone https://github.com/fincs/dekotools.git --depth 1
        cd dekotools
        meson setup build
        ninja -C build install
    - name: Build portlibs
      run: |
        adduser --gecos '' --disabled-password builder
        echo 'builder ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/builder

        curl -o scripts/switch/mpv-deko3d/deko3d.patch \
          -H 'Accept: application/vnd.github.patch' \
          -H 'Authorization: Bearer ${{ secrets.MPV_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -s ${{ secrets.MPV_COMMIT}}

        chown -R builder:builder ${GITHUB_WORKSPACE}/scripts/switch
        sudo -u builder -i bash -s << EOF
          cd ${GITHUB_WORKSPACE}/scripts/switch
          for pkg in curl harfbuzz libass dav1d ffmpeg deko3d libuam; do
            echo building \$pkg
            cd \$pkg; dkp-makepkg -sciCf --noconfirm; cd ..
          done
          for pkg in mpv mpv-deko3d nspmini hacbrewpack; do
            echo building \$pkg
            cd \$pkg; dkp-makepkg -scCf --noconfirm; cd ..
          done
        EOF
    - name: Upload portlibs
      uses: softprops/action-gh-release@v1
      with:
        name: switch-portlibs
        tag_name: switch-portlibs
        prerelease: true
        files: scripts/switch/*/*.pkg.tar.zst
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/switch-portlibs/total?label=Downloads)